### PR TITLE
Update software.txt

### PR DESCRIPTION
**Pull request by sbasegmez**
Added Domino REST API 1.0.12

### CODE REVIEW

**Comment by Daniel-Nashed** [comment]
Hi @sbasegmez!

Thanks for your request! 
Usually changes are going into the **develop** branch first, before merging them into **main**.
**software.txt** changes are kind of special and I think it would be time to add another software branch to be able to push software faster into the **main** branch, when we have pending changes in the **develop** branch.

Also all changes need to pass the automation test, which I am running usually first on new software before merging them.

The changes you are pulling in are already in the **develop** branch. But we have other pending changes. 
Because I am submitting 95% of the content, we have no bigger branch management. But **software.txt** and **current_version.txt** are special cases.

I don't want to block new software because of pending changes in the **develop** branch where we want others to test, before we merge them into **main**.

I will just merge my changes including the software.txt and current version file.

**Comment by Daniel-Nashed** [comment]
I merged the develop branch to main. But I will look into a better way managing the software.
What I would like to do in the long run is to use software.jwt from Domino autoupdate.
But it does only contain Notes, Domino and Traveler.

**Comment by Daniel-Nashed** [comment]
Did you know you can use your own version of **software.txt** and **current_version.txt**  stored in an external software directory specified by `SOFTWARE_DIR` or `DOWNLOAD_FROM`. 
This allows you to bring up a newer version of the files.

For Git repo reasons I need to revisit again, the files are stored twice. we need it to check the software before starting the build process and the build container also needs it to validate the hashes.

**Comment by sbasegmez** [comment]
Hi Daniel, 

Normally, I don't need to upgrade to the latest release immediately. This version of DRAPI was an exception. I learned how to do it now. I agree. There should be a better way to handle this in the future but having the chance to override it manually is enough for now.

Thanks for resolving the issue.

**Comment by Daniel-Nashed** [comment]
You can make any change to the software.txt. 
Currently the GitHub project is the gatekeeper for the software.txt and if we would move it to a different place, this would make it more complicated.

This way you only need the project and no external connection. 
We would need a place where we store the software.txt. 

For the HCL software.jwt this is a signed file provided by HCL on one of their servers.
The community project is using GitHub. 

It's customizable today by having your own version and we are usually pushing the changes out quick.
I will bring this up again to see how we could improve it.

But this comes from the very early days of the repository when Thomas started it and we can't quickly change it without introduces changes for existing users.

We could offer new options, but they would need to be secure. 

What I would really like would be a software.jwt with all software and a public key we could use to validate it.
I did hear that at Engage from a couple of admins having the public key available for domdownload to validate software after download on top of just having the SHA256 in software.txt .

Also we have some additional software listed. For example Borg Backup and Tika. 
They are listed with their hashes to ensure you get the validated versions.
That's clearly a community offering and not a direct HCL offering.

So for now I think it is best to stay with software.txt and provide the option to modify it.

**Pull request closed without merging**
